@host = http://localhost:4000

### Create Product
POST {{host}}/api/create-product
Content-Type: application/json

{
}

### List all products
GET {{host}}/api/list-all-products


### Delete product by id
DELETE {{host}}/api/delete-product-by-id
Content-Type: application/json

{
    "id": 8
}